development:
  adapter: postgresql
  encoding: utf8
  database: codex_development
  host: localhost
  pool: 5
  timeout: 5000
  username: danielrassiner
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: codex_test
  pool: 5
  timeout: 5000
  username: danielrassiner
  password:
